version: '3.4'

networks:
  net:

volumes:
  postgres_data:
    driver: local

services:
  db:
    image: postgres
    container_name: hexchan_db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - net
    volumes:
      - postgres_data:/var/lib/postgresql

  app:
    build: .
    container_name: hexchan_app
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - FAKE_CONTENT=true
    ports:
      - 8000:8000
    networks:
      - net
    depends_on:
      - db
    links:
      - db
