version: '3.4'

networks:
  net:

volumes:
  hexchan_pg_data:
    driver: local

services:
  db:
    image: postgres:11-alpine
    container_name: hexchan_db
    restart: always
    environment:
      - POSTGRES_DB=hexchan
      - POSTGRES_USER=hexchan
      - POSTGRES_PASSWORD=hexchan
    networks:
      - net
    volumes:
      - hexchan_pg_data:/var/lib/postgresql/data

  app:
    build: .
    image: hexchan
    container_name: hexchan_app
    restart: always
    environment:
      - FAKE_CONTENT=False
      - DEBUG=False
      - DB_HOST=hexchan_db
      - DB_PORT=5432
      - DB_NAME=hexchan
      - DB_USER=hexchan
      - DB_PASSWORD=hexchan
      - ALLOWED_HOSTS=warriorpath.online,www.warriorpath.online,45.146.165.216
    ports:
      - "8081:8000"
    networks:
      - net
    depends_on:
      - db
    links:
      - db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: hexchan_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - net