version: '3.4'

networks:
  net:

volumes:
  hexchan_pg_data:
    driver: local

services:
  db:
    image: postgres
    container_name: hexchan_db
    restart: always
    environment:
      - POSTGRES_DB=hexchan
      - POSTGRES_USER=hexchan
      - POSTGRES_PASSWORD=hexchan
    networks:
      - net
    volumes:
      - hexchan_pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: hexchan_app
    restart: always
    environment:
      - POSTGRES_PASSWORD=hexchan
      - FAKE_CONTENT=false
    ports:
      - 8000:8000
    networks:
      - net
    depends_on:
      - db
    links:
      - db
