version: '3.4'

networks:
  net:
    driver: overlay

volumes:
  hexchan_pg_data:
    driver: local

services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=hexchan
      - POSTGRES_USER=hexchan
      - POSTGRES_PASSWORD=hexchan
    networks:
      - net
    volumes:
      - hexchan_pg_data:/var/lib/postgresql/data

  app:
    image: hexchan:latest
    environment:
      - FAKE_CONTENT=False
      - DEBUG=False
      - DB_HOST=hexchan_db
      - DB_PORT=5432
      - DB_NAME=hexchan
      - DB_USER=hexchan
      - DB_PASSWORD=hexchan
    ports:
      - 80:80
      - 443:443
    networks:
      - net
    depends_on:
      - db
